spring:
  application:
    name: eureka-server
  security:
    user:
      name: ms-eurekauser
      password: 123456

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



