spring:
  application:
    name: mscards
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://ms-eurekauser:123456@localhost:8761/eureka
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

mq:
  queues:
    card-emission: card-emission
